spring:
  datasource:
    url: jdbc:h2:tcp://localhost/~/board
    username: sa
    password:
    driver-class-name: org.h2.Driver
  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        show_sql: true
        default_batch_fetch_size: 100
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher

  messages:
    basename: exp/messages

jwt:
  secret:  cmxhZWhkZG5kZG1sdG12bWZsZHJoZHFudm1maHdwcnhtdAo= # echo 'rlaehddnddmltmvmfldrhdqnvmfhwprxmt'|base64
  token-validity-in-seconds:  86400

upload:
  image:
    location: /Users/kdo6301/Desktop/springFile/

default:
  page:
    size: 5
    num: 0